version: "3.9"
services:
  web:
    container_name: django_project_structure_web
    build: .
    # command: uv run manage.py runserver 0.0.0.0:8000
    command: []
    entrypoint: ["/entrypoint.sh"]
    restart: always
    volumes:
      - .:/app:cached # optimize for macOS; remove for production
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DEBUG: "TRUE"

  db:
    container_name: django_project_structure_db
    image: postgres:17-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5451:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  redis:
    container_name: django_project_structure_cache
    image: redis:8.0-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
